apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: definition
spec:
  service:
    type: LoadBalancer
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    # limits:
    #   cpu: 800m
    #   memory: 1Gi
